_wandb:
    value:
        cli_version: 0.24.0
        e:
            n5kwtidaci3c7klu6r1itnpemdjoqu1t:
                args:
                    - train
                    - --preprocessed-folder
                    - data/preprocessed
                    - --epochs
                    - "10"
                    - --batch-size
                    - "32"
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "355266985984"
                        used: "72888942592"
                email: guido.biosca@estudiantat.upc.edu
                executable: /home/guidobioska/miniconda3/envs/mlops_env/bin/python
                git:
                    commit: 261d917da56faded434c84ef6d3349ae70b1ed0d
                    remote: git@github.com:BioscaG/energy-disaggregation-mlops.git
                host: guidobioska
                memory:
                    total: "16559116288"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: -m energy_dissagregation_mlops.cli
                python: CPython 3.12.12
                root: /home/guidobioska/Documents/DTU/energy-disaggregation-mlops
                startedAt: "2026-01-17T15:19:28.493858Z"
                writerId: n5kwtidaci3c7klu6r1itnpemdjoqu1t
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 1
                - 16
                - 61
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 32
device:
    value: cpu
epochs:
    value: 10
lr:
    value: 0.0001
num_workers:
    value: 2
preprocessed_folder:
    value: data/preprocessed
