_wandb:
    value:
        cli_version: 0.24.0
        e:
            rdj270xrnzrsjz1605hlym0n7vpwxngg:
                codePath: scripts/run_sweep.py
                codePathLocal: scripts/run_sweep.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "355266985984"
                        used: "72891768832"
                email: guido.biosca@estudiantat.upc.edu
                executable: /home/guidobioska/miniconda3/envs/mlops_env/bin/python
                git:
                    commit: 261d917da56faded434c84ef6d3349ae70b1ed0d
                    remote: git@github.com:BioscaG/energy-disaggregation-mlops.git
                host: guidobioska
                memory:
                    total: "16559116288"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/guidobioska/Documents/DTU/energy-disaggregation-mlops/scripts/run_sweep.py
                python: CPython 3.12.12
                root: /home/guidobioska/Documents/DTU/energy-disaggregation-mlops
                startedAt: "2026-01-17T15:12:58.865675Z"
                writerId: rdj270xrnzrsjz1605hlym0n7vpwxngg
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 24
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
