_wandb:
    value:
        cli_version: 0.24.0
        e:
            m99b5bc41ntf3dzxp0s9lgrf0hcruz0e:
                codePath: scripts/run_sweep.py
                codePathLocal: scripts/run_sweep.py
                email: guido.biosca@estudiantat.upc.edu
                executable: /home/guidobioska/miniconda3/envs/mlops_env/bin/python
                git:
                    commit: 261d917da56faded434c84ef6d3349ae70b1ed0d
                    remote: git@github.com:BioscaG/energy-disaggregation-mlops.git
                host: guidobioska
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/guidobioska/Documents/DTU/energy-disaggregation-mlops/scripts/run_sweep.py
                python: CPython 3.12.12
                root: /home/guidobioska/Documents/DTU/energy-disaggregation-mlops
                startedAt: "2026-01-17T15:12:16.762566Z"
                writerId: m99b5bc41ntf3dzxp0s9lgrf0hcruz0e
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
