_wandb:
    value:
        cli_version: 0.24.0
        e:
            dbramfer12v02uvrc1zlkpb0qu9dr8x5:
                args:
                    - train
                    - --preprocessed-folder
                    - data/preprocessed
                    - --epochs
                    - "10"
                    - --batch-size
                    - "32"
                email: guido.biosca@estudiantat.upc.edu
                executable: /home/guidobioska/miniconda3/envs/mlops_env/bin/python
                git:
                    commit: 593385d25bf789ecf91a47ce39b889af42075b4b
                    remote: git@github.com:BioscaG/energy-disaggregation-mlops.git
                host: guidobioska
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: -m energy_dissagregation_mlops.cli
                python: CPython 3.12.12
                root: /home/guidobioska/Documents/DTU/energy-disaggregation-mlops
                startedAt: "2026-01-17T15:27:27.880872Z"
                writerId: dbramfer12v02uvrc1zlkpb0qu9dr8x5
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 16
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 32
device:
    value: cpu
epochs:
    value: 10
lr:
    value: 0.0001
num_workers:
    value: 2
preprocessed_folder:
    value: data/preprocessed
